/**
 * Central icon registry.
 * Re-export the lucide-react icons the app uses so imports stay consistent and
 * the icon set is easy to audit/swap. Import via `import { Icons } from "@/components/icons"`.
 */
import {
  LayoutDashboard,
  Settings,
  Users,
  Bell,
  Search,
  Menu,
  X,
  ChevronDown,
  ChevronRight,
  LogOut,
  Plus,
  Loader2,
  Mail,
  Lock,
  Eye,
  EyeOff,
  User,
  BarChart3,
  PanelLeft,
  PanelLeftClose,
  TrendingUp,
  TrendingDown,
  Wallet,
  ArrowLeftRight,
  Coins,
  Activity,
  Receipt,
  Shield,
  ShieldCheck,
  BadgeCheck,
  MapPin,
  Calendar,
  Phone,
  Filter,
  UserPlus,
  Globe,
  Moon,
  Check,
  CreditCard,
  Clock,
  Key,
  Smartphone,
  MoreHorizontal,
  Copy,
  Camera,
  LogIn,
  SquarePen,
  Trash2,
  Ban,
  ArrowUpDown,
  ArrowUp,
  ArrowDown,
  ChevronLeft,
  LockOpen,
  AlertTriangle,
  ExternalLink,
  Hash,
  Landmark,
  SlidersHorizontal,
  Network,
  Percent,
  DollarSign,
  Building2,
  Link2,
  RefreshCw,
  Tag,
  CheckCircle2,
  XCircle,
  UserCog,
  ShieldAlert,
  Bookmark,
  Layers,
  type LucideIcon,
} from "lucide-react";

export type Icon = LucideIcon;

export const Icons = {
  dashboard: LayoutDashboard,
  settings: Settings,
  users: Users,
  bell: Bell,
  search: Search,
  menu: Menu,
  close: X,
  chevronDown: ChevronDown,
  chevronRight: ChevronRight,
  logout: LogOut,
  plus: Plus,
  spinner: Loader2,
  mail: Mail,
  lock: Lock,
  eye: Eye,
  eyeOff: EyeOff,
  user: User,
  analytics: BarChart3,
  panelLeft: PanelLeft,
  panelLeftClose: PanelLeftClose,
  trendingUp: TrendingUp,
  trendingDown: TrendingDown,
  wallet: Wallet,
  swap: ArrowLeftRight,
  coins: Coins,
  activity: Activity,
  receipt: Receipt,
  shield: Shield,
  shieldCheck: ShieldCheck,
  badgeCheck: BadgeCheck,
  mapPin: MapPin,
  calendar: Calendar,
  phone: Phone,
  filter: Filter,
  userPlus: UserPlus,
  globe: Globe,
  moon: Moon,
  check: Check,
  creditCard: CreditCard,
  clock: Clock,
  key: Key,
  smartphone: Smartphone,
  more: MoreHorizontal,
  copy: Copy,
  camera: Camera,
  login: LogIn,
  edit: SquarePen,
  trash: Trash2,
  ban: Ban,
  sort: ArrowUpDown,
  arrowUp: ArrowUp,
  arrowDown: ArrowDown,
  chevronLeft: ChevronLeft,
  unlock: LockOpen,
  alertTriangle: AlertTriangle,
  externalLink: ExternalLink,
  hash: Hash,
  landmark: Landmark,
  sliders: SlidersHorizontal,
  network: Network,
  percent: Percent,
  dollar: DollarSign,
  building: Building2,
  link: Link2,
  refresh: RefreshCw,
  tag: Tag,
  checkCircle: CheckCircle2,
  xCircle: XCircle,
  userCog: UserCog,
  shieldAlert: ShieldAlert,
  bookmark: Bookmark,
  layers: Layers,
} as const;
